from time import sleep

print()
print('Hi Bhai Anil')
sleep(1)
print('\tbol bhai Sunil'.expandtabs(2))
sleep(1)
print('\n\tbhai ye hai a = 3'.expandtabs(2))
sleep(1)
print('\tbhai ye hai b = 0'.expandtabs(2))
sleep(1)

print('\n\tjab tak bhai (b < 5) {'.expandtabs(2))
sleep(1)
print('\t\tbol bhai b'.expandtabs(2))
sleep(1)
print('\n\t\tagar bhai (b == a)'.expandtabs(2))
sleep(1)
print('\t\t\tbol bhai "b is equal to a";'.expandtabs(2))
sleep(1)
print('\t\t}'.expandtabs(2))
print('😀')
sleep(10)
